# Generated by Django 5.1.3 on 2025-12-26 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='Название класса')),
            ],
            options={
                'verbose_name': '@Классы ТС мойки',
                'verbose_name_plural': '@Классы ТС мойки',
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='Тип')),
            ],
            options={
                'verbose_name': '>Типы оплаты',
                'verbose_name_plural': '>Типы оплаты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Без имени', max_length=32, verbose_name='Название')),
            ],
            options={
                'verbose_name': '>Список услуг мойки',
                'verbose_name_plural': '>Список услуг мойки',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': '#Список смен',
                'verbose_name_plural': '#Список смен',
            },
        ),
        migrations.CreateModel(
            name='Washman',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
                ('is_active', models.BooleanField(default='True', verbose_name='Активность')),
            ],
            options={
                'verbose_name': '#Список мойщиков',
                'verbose_name_plural': '#Список мойщиков',
            },
        ),
        migrations.CreateModel(
            name='Wash',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время')),
                ('grz', models.CharField(default='а000аа000', max_length=9, verbose_name='ГРЗ')),
                ('mark', models.CharField(default='Марка', max_length=32, verbose_name='Марка')),
                ('night', models.BooleanField(default=False, verbose_name='Ночная')),
                ('dry', models.BooleanField(default=False, verbose_name='Химчистка')),
                ('polishing', models.BooleanField(default=False, verbose_name='Полировка')),
                ('sale', models.PositiveIntegerField(default=0, verbose_name='Скидка')),
                ('add', models.IntegerField(default=0, verbose_name='Добавочная стоимость')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('washman_money', models.FloatField(default=0, verbose_name='Процент мойщика')),
                ('car_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carclass', verbose_name='Класс авто')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.pay', verbose_name='Тип оплаты')),
                ('service', models.ManyToManyField(blank=True, to='carwash.service', verbose_name='Услуги')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.shift', verbose_name='Смена')),
                ('washman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.washman', verbose_name='Мойщик')),
            ],
            options={
                'verbose_name': '#Список моек',
                'verbose_name_plural': '#Список моек',
            },
        ),
        migrations.CreateModel(
            name='WashPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('car_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.carclass', verbose_name='Класс авто')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': '%Прайс-лист мойки',
                'verbose_name_plural': '%Прайс-лист мойки',
                'unique_together': {('service', 'car_class')},
            },
        ),
    ]
