# Generated by Django 3.2.16 on 2023-07-24 18:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarClass',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='Название класса')),
            ],
            options={
                'verbose_name': 'Класс',
                'verbose_name_plural': 'Класс',
            },
        ),
        migrations.CreateModel(
            name='Pay',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=32, verbose_name='Тип')),
            ],
            options={
                'verbose_name': 'Тип оплаты',
                'verbose_name_plural': 'Тип оплаты',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Без имени', max_length=32, verbose_name='Название')),
                ('price1', models.IntegerField(default=0, verbose_name='Стоимость 1 класса')),
                ('price2', models.IntegerField(default=0, verbose_name='Стоимость 2 класса')),
                ('price3', models.IntegerField(default=0, verbose_name='Стоимость 3 класса')),
                ('price4', models.IntegerField(default=0, verbose_name='Стоимость 4 класса')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуга',
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(unique=True, verbose_name='Дата')),
            ],
            options={
                'verbose_name': 'Дата',
                'verbose_name_plural': 'Дата',
            },
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Не названа', max_length=32, verbose_name='Название')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предмет',
            },
        ),
        migrations.CreateModel(
            name='Washman',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=64, verbose_name='Имя')),
                ('balance', models.IntegerField(default=0, verbose_name='Баланс')),
            ],
            options={
                'verbose_name': 'Мойщик',
                'verbose_name_plural': 'Мойщик',
            },
        ),
        migrations.CreateModel(
            name='Wash',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('time', models.TimeField(auto_now_add=True, verbose_name='Время')),
                ('grz', models.CharField(default='а000аа000', max_length=9, verbose_name='ГРЗ')),
                ('mark', models.CharField(default='Марка', max_length=32, verbose_name='Марка')),
                ('night', models.BooleanField(default=False, verbose_name='Ночная')),
                ('dry', models.BooleanField(default=False, verbose_name='Химчистка')),
                ('polishing', models.BooleanField(default=False, verbose_name='Рлировка')),
                ('sale', models.PositiveIntegerField(default=0, verbose_name='Скидка')),
                ('add', models.IntegerField(default=0, verbose_name='Добавочная стоимость')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('car_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carclass', verbose_name='Класс авто')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pay', verbose_name='Тип оплаты')),
                ('service', models.ManyToManyField(blank=True, null=True, to='core.Service', verbose_name='Услуги')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shift', verbose_name='Смена')),
                ('washman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.washman', verbose_name='Мойщик')),
            ],
            options={
                'verbose_name': 'Мойка',
                'verbose_name_plural': 'Мойка',
            },
        ),
        migrations.CreateModel(
            name='StockConsumption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('money', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.pay', verbose_name='Тип оплаты')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shift', verbose_name='Смена')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stock', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Отчёт склада',
                'verbose_name_plural': 'Отчёт склада',
            },
        ),
        migrations.CreateModel(
            name='OtherConsumption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=32, verbose_name='Описание')),
                ('money', models.IntegerField(default=0, verbose_name='Сумма')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.shift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': 'Бытовые расходы',
                'verbose_name_plural': 'Бытовые расходы',
            },
        ),
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('money', models.IntegerField(default=0, verbose_name='Выплата')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.shift', verbose_name='Смена')),
                ('washman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.washman', verbose_name='Мойщик')),
            ],
            options={
                'verbose_name': 'Выплата',
                'verbose_name_plural': 'Выплата',
            },
        ),
    ]
