# Generated by Django 3.2.16 on 2023-07-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=64, verbose_name='Описание')),
                ('wash', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.wash', verbose_name='Мойка')),
            ],
            options={
                'verbose_name': 'Запрос мойки',
                'verbose_name_plural': 'Запрос мойки',
            },
        ),
        migrations.CreateModel(
            name='RequestStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=64, verbose_name='Описание')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stockconsumption', verbose_name='Приход')),
            ],
            options={
                'verbose_name': 'Запрос склада',
                'verbose_name_plural': 'Запрос склада',
            },
        ),
        migrations.CreateModel(
            name='RequestOtherConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=64, verbose_name='Описание')),
                ('consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.otherconsumption', verbose_name='Расход')),
            ],
            options={
                'verbose_name': 'Запрос бытовой расход',
                'verbose_name_plural': 'Запрос бытовой расход',
            },
        ),
        migrations.CreateModel(
            name='RequestConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=64, verbose_name='Описание')),
                ('consumption', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.consumption', verbose_name='Расход')),
            ],
            options={
                'verbose_name': 'Запрос расход',
                'verbose_name_plural': 'Запрос расход',
            },
        ),
    ]
