# Generated by Django 3.2.16 on 2023-08-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_requestconsumption_requestotherconsumption_requeststock_requestwash'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carclass',
            options={'verbose_name': '1.2 Классы авто', 'verbose_name_plural': '1.2 Классы авто'},
        ),
        migrations.AlterModelOptions(
            name='consumption',
            options={'verbose_name': '4.1 Выплаты мойщикам', 'verbose_name_plural': '4.1 Выплаты мойщикам'},
        ),
        migrations.AlterModelOptions(
            name='otherconsumption',
            options={'verbose_name': '4.3 Отчёты бытовые', 'verbose_name_plural': '4.3 Отчёты бытовые'},
        ),
        migrations.AlterModelOptions(
            name='pay',
            options={'verbose_name': '1.3 Типы оплаты', 'verbose_name_plural': '1.3 Типы оплаты'},
        ),
        migrations.AlterModelOptions(
            name='requestconsumption',
            options={'verbose_name': '5.3 Запрос расход', 'verbose_name_plural': '5.3 Запрос расход'},
        ),
        migrations.AlterModelOptions(
            name='requestotherconsumption',
            options={'verbose_name': '5.4 Запрос бытовой расход', 'verbose_name_plural': '5.4 Запрос бытовой расход'},
        ),
        migrations.AlterModelOptions(
            name='requeststock',
            options={'verbose_name': '5.2 Запрос склада', 'verbose_name_plural': '5.2 Запрос склада'},
        ),
        migrations.AlterModelOptions(
            name='requestwash',
            options={'verbose_name': '5.1 Запрос мойки', 'verbose_name_plural': '5.1 Запрос мойки'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '1.4 Список услуг', 'verbose_name_plural': '1.4 Список услуг'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': '2. Список смен', 'verbose_name_plural': '2. Список смен'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': '3. Склад', 'verbose_name_plural': '3. Склад'},
        ),
        migrations.AlterModelOptions(
            name='stockconsumption',
            options={'verbose_name': '4.2 Отчёты склада', 'verbose_name_plural': '4.2 Отчёты склада'},
        ),
        migrations.AlterModelOptions(
            name='wash',
            options={'verbose_name': '1. Список моек', 'verbose_name_plural': '1. Список моек'},
        ),
        migrations.AlterModelOptions(
            name='washman',
            options={'verbose_name': '1.1 Список мойщиков', 'verbose_name_plural': '1.1 Список мойщиков'},
        ),
        migrations.AddField(
            model_name='requestconsumption',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='requestotherconsumption',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='requeststock',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AddField(
            model_name='requestwash',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Активна'),
        ),
        migrations.AlterField(
            model_name='requeststock',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='requestwash',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
