# Generated by Django 3.2.16 on 2023-08-04 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20230803_1919'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requeststock',
            old_name='stock',
            new_name='obj',
        ),
        migrations.RenameField(
            model_name='requestwash',
            old_name='wash',
            new_name='obj',
        ),
    ]
