# Generated by Django 3.2.16 on 2023-08-04 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_requeststock_obj'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requeststock',
            name='obj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.stockconsumption', verbose_name='Приход'),
        ),
    ]
