# Generated by Django 3.2.16 on 2023-08-05 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_requeststock_obj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='requestconsumption',
            old_name='consumption',
            new_name='obj',
        ),
        migrations.RenameField(
            model_name='requestotherconsumption',
            old_name='consumption',
            new_name='obj',
        ),
    ]
