# Generated by Django 3.2.16 on 2023-08-05 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20230805_1258'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestconsumption',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='requestotherconsumption',
            name='description',
            field=models.TextField(default='', verbose_name='Описание'),
        ),
    ]
