# Generated by Django 3.2.16 on 2023-09-02 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20230805_1301'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wash',
            name='polishing',
            field=models.BooleanField(default=False, verbose_name='Полировка'),
        ),
    ]
