# Generated by Django 3.2.16 on 2023-09-02 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_wash_polishing'),
    ]

    operations = [
        migrations.AddField(
            model_name='washman',
            name='is_active',
            field=models.BooleanField(default='True', verbose_name='Активность'),
        ),
    ]
