# Generated by Django 3.2.23 on 2023-12-07 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_washman_is_active'),
    ]

    operations = [
        migrations.CreateModel(
            name='WashPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('car_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carclass', verbose_name='Класс авто')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': '6.1 Прайс-лист мойки',
                'verbose_name_plural': '6.1 Прайс-лист мойки',
            },
        ),
        migrations.CreateModel(
            name='CarshPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('car_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carclass', verbose_name='Класс авто')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': '6.1 Прайс-лист мойки',
                'verbose_name_plural': '6.1 Прайс-лист мойки',
            },
        ),
    ]
