# Generated by Django 3.2.23 on 2023-12-07 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_carshpricelist_washpricelist'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carshpricelist',
            options={'verbose_name': '6.2 Прайс-лист каршеринга', 'verbose_name_plural': '6.2 Прайс-лист каршеринга'},
        ),
        migrations.RemoveField(
            model_name='service',
            name='price1',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price2',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price3',
        ),
        migrations.RemoveField(
            model_name='service',
            name='price4',
        ),
        migrations.AlterUniqueTogether(
            name='washpricelist',
            unique_together={('service', 'car_class')},
        ),
    ]
