# Generated by Django 3.2.23 on 2023-12-07 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20231208_0123'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarshCarClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название класса')),
            ],
            options={
                'verbose_name': '1.2.1 Классы каршеринга',
                'verbose_name_plural': '1.2.1 Классы каршеринга',
            },
        ),
        migrations.CreateModel(
            name='CarshService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Без имени', max_length=32, verbose_name='Название')),
            ],
            options={
                'verbose_name': '1.4.1 Список услуг каршеринга',
                'verbose_name_plural': '1.4.1 Список услуг каршеринга',
            },
        ),
    ]
