# Generated by Django 3.2.23 on 2023-12-08 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_carshcarclass_carshservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carclass',
            options={'verbose_name': '@Классы ТС мойки', 'verbose_name_plural': '@Классы ТС мойки'},
        ),
        migrations.AlterModelOptions(
            name='carshcarclass',
            options={'verbose_name': '@Классы ТС каршеринга', 'verbose_name_plural': '@Классы ТС каршеринга'},
        ),
        migrations.AlterModelOptions(
            name='carshpricelist',
            options={'verbose_name': '%Прайс-лист каршеринга', 'verbose_name_plural': '%Прайс-лист каршеринга'},
        ),
        migrations.AlterModelOptions(
            name='carshservice',
            options={'verbose_name': '>Список услуг каршеринга', 'verbose_name_plural': '>Список услуг каршеринга'},
        ),
        migrations.AlterModelOptions(
            name='consumption',
            options={'verbose_name': '$Выплаты мойщикам', 'verbose_name_plural': '$Выплаты мойщикам'},
        ),
        migrations.AlterModelOptions(
            name='otherconsumption',
            options={'verbose_name': '$Отчёты бытовые', 'verbose_name_plural': '$Отчёты бытовые'},
        ),
        migrations.AlterModelOptions(
            name='pay',
            options={'verbose_name': '>Типы оплаты', 'verbose_name_plural': '>Типы оплаты'},
        ),
        migrations.AlterModelOptions(
            name='requestconsumption',
            options={'verbose_name': "'Запрос расход", 'verbose_name_plural': "'Запрос расход"},
        ),
        migrations.AlterModelOptions(
            name='requestotherconsumption',
            options={'verbose_name': "'Запрос бытовой расход", 'verbose_name_plural': "'Запрос бытовой расход"},
        ),
        migrations.AlterModelOptions(
            name='requeststock',
            options={'verbose_name': "'Запрос склада", 'verbose_name_plural': "'Запрос склада"},
        ),
        migrations.AlterModelOptions(
            name='requestwash',
            options={'verbose_name': "'Запрос мойки", 'verbose_name_plural': "'Запрос мойки"},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': '>Список услуг мойки', 'verbose_name_plural': '>Список услуг мойки'},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={'verbose_name': '#Список смен', 'verbose_name_plural': '#Список смен'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': '#Склад', 'verbose_name_plural': '#Склад'},
        ),
        migrations.AlterModelOptions(
            name='stockconsumption',
            options={'verbose_name': '$Отчёты склада', 'verbose_name_plural': '$Отчёты склада'},
        ),
        migrations.AlterModelOptions(
            name='wash',
            options={'verbose_name': '#Список моек', 'verbose_name_plural': '#Список моек'},
        ),
        migrations.AlterModelOptions(
            name='washman',
            options={'verbose_name': '#Список мойщиков', 'verbose_name_plural': '#Список мойщиков'},
        ),
        migrations.AlterModelOptions(
            name='washpricelist',
            options={'verbose_name': '%Прайс-лист мойки', 'verbose_name_plural': '%Прайс-лист мойки'},
        ),
        migrations.AddField(
            model_name='wash',
            name='washman_money',
            field=models.IntegerField(default=0, verbose_name='Процент мойщика'),
        ),
        migrations.AlterField(
            model_name='carshpricelist',
            name='car_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carshcarclass', verbose_name='Класс авто'),
        ),
        migrations.AlterField(
            model_name='carshpricelist',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.carshservice', verbose_name='Услуга'),
        ),
    ]
