# Generated by Django 3.2.23 on 2023-12-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_auto_20231209_0148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wash',
            name='washman_money',
            field=models.FloatField(default=0, verbose_name='Процент мойщика'),
        ),
    ]
