# Generated by Django 3.2.23 on 2023-12-08 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_alter_wash_washman_money'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumption',
            name='money',
            field=models.FloatField(default=0, verbose_name='Выплата'),
        ),
    ]
