# Generated by Django 5.0 on 2023-12-12 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_alter_consumption_money'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=32, verbose_name='Название')),
                ('admin_part', models.FloatField(default=0.0, help_text='Ставка администратора до преодоления порога кассы.', verbose_name='Ставка администратора')),
                ('cash_treshhold', models.FloatField(default=0.0, help_text='Порог кассы, после которого администратор начнёт получать процент с прибыли.', verbose_name='Порог кассы')),
                ('cash_treshhold_percent', models.FloatField(default=0.0, help_text='Процент который получит администратор при преодолении порога кассы.', verbose_name='Процент порога')),
                ('night_sale', models.FloatField(default=0.0, help_text='Скидка на ночные мойки. Пример: 0.5 = 50%', verbose_name='Ночная скидка')),
                ('washman_percent', models.FloatField(default=0.0, help_text='Процет который получит мойщик с обычной мойки. Пример: 0.5 = 50%', verbose_name='Процент мойщика')),
                ('washman_dry_percent', models.FloatField(default=0.0, help_text='Процент который мойщик получает с химчисток. Пример: 0.5 = 50%', verbose_name='Процент мойщика с химчистки')),
                ('washman_poly_percent', models.FloatField(default=0.0, help_text='Процент который мойщик получает с полировки. Приер: 0.5 = 50%', verbose_name='Процент мойщика с полировки')),
                ('is_active', models.BooleanField(default=False, help_text='Активность конфигурации', verbose_name='Активность')),
            ],
            options={
                'verbose_name': 'Настрока',
                'verbose_name_plural': 'Настрока',
            },
        ),
        migrations.AlterUniqueTogether(
            name='carshpricelist',
            unique_together={('service', 'car_class')},
        ),
    ]
