# Generated by Django 5.0 on 2023-12-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_settings_alter_carshpricelist_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='washman_night_percent',
            field=models.FloatField(default=0.0, help_text='Процент который получит мойщик с ночной мойки. Пример: 0,5 = 50%', verbose_name='Ночной процент мойщика'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='cash_treshhold_percent',
            field=models.FloatField(default=0.0, help_text='Процент который получит администратор при преодолении порога кассы. Пример: 0,5 = 50%', verbose_name='Процент порога'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='night_sale',
            field=models.FloatField(default=0.0, help_text='Скидка на ночные мойки. Пример: 0,5 = 50%', verbose_name='Ночная скидка'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='washman_dry_percent',
            field=models.FloatField(default=0.0, help_text='Процент который мойщик получает с химчисток. Пример: 0,5 = 50%', verbose_name='Процент мойщика с химчистки'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='washman_percent',
            field=models.FloatField(default=0.0, help_text='Процет который получит мойщик с обычной мойки. Пример: 0,5 = 50%', verbose_name='Процент мойщика'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='washman_poly_percent',
            field=models.FloatField(default=0.0, help_text='Процент который мойщик получает с полировки. Пример: 0,5 = 50%', verbose_name='Процент мойщика с полировки'),
        ),
    ]
