# Generated by Django 5.0 on 2024-10-29 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_settings_washman_night_percent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='is_visible',
            field=models.BooleanField(default=False, verbose_name='Видимость'),
        ),
    ]
