# Generated by Django 5.1.3 on 2025-12-26 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(default='Не названа', max_length=32, verbose_name='Название')),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('price', models.IntegerField(default=0, verbose_name='Цена')),
                ('is_visible', models.BooleanField(default=False, verbose_name='Видимость')),
            ],
            options={
                'verbose_name': '#Склад',
                'verbose_name_plural': '#Склад',
            },
        ),
        migrations.CreateModel(
            name='StockConsumption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(default=0, verbose_name='Количество')),
                ('money', models.IntegerField(default=0, verbose_name='Стоимость')),
                ('pay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.pay', verbose_name='Тип оплаты')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.shift', verbose_name='Смена')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.stock', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': '$Отчёты склада',
                'verbose_name_plural': '$Отчёты склада',
            },
        ),
    ]
