# Generated by Django 5.1.3 on 2025-12-26 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CarshCarClass',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название класса')),
            ],
            options={
                'verbose_name': '@Классы ТС каршеринга',
                'verbose_name_plural': '@Классы ТС каршеринга',
            },
        ),
        migrations.CreateModel(
            name='CarshService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Без имени', max_length=32, verbose_name='Название')),
            ],
            options={
                'verbose_name': '>Список услуг каршеринга',
                'verbose_name_plural': '>Список услуг каршеринга',
            },
        ),
        migrations.CreateModel(
            name='CarshPriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.IntegerField(verbose_name='Стоимость')),
                ('car_class', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsharing.carshcarclass', verbose_name='Класс авто')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carsharing.carshservice', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': '%Прайс-лист каршеринга',
                'verbose_name_plural': '%Прайс-лист каршеринга',
                'unique_together': {('service', 'car_class')},
            },
        ),
    ]
