# Generated by Django 5.1.3 on 2025-12-26 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounting', '0001_initial'),
        ('carwash', '0001_initial'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.consumption', verbose_name='Расход')),
            ],
            options={
                'verbose_name': "'Запрос расход",
                'verbose_name_plural': "'Запрос расход",
            },
        ),
        migrations.CreateModel(
            name='RequestOtherConsumption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounting.otherconsumption', verbose_name='Расход')),
            ],
            options={
                'verbose_name': "'Запрос бытовой расход",
                'verbose_name_plural': "'Запрос бытовой расход",
            },
        ),
        migrations.CreateModel(
            name='RequestStock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='warehouse.stockconsumption', verbose_name='Приход')),
            ],
            options={
                'verbose_name': "'Запрос склада",
                'verbose_name_plural': "'Запрос склада",
            },
        ),
        migrations.CreateModel(
            name='RequestWash',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(default='', verbose_name='Описание')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('obj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.wash', verbose_name='Мойка')),
            ],
            options={
                'verbose_name': "'Запрос мойки",
                'verbose_name_plural': "'Запрос мойки",
            },
        ),
    ]
