"""
Django settings for site1 project.

Generated by 'django-admin startproject' using Django 3.2.16.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

# Загрузка переменных окружения из .env файла
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-a6_!=5=2v1)b#e2xv0@=6&r-pmtsl0x^_q2-z0#h-3683ta0jo')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'True').lower() == 'true'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', 'localhost,127.0.0.1,*.railway.app,railway.app').split(',')

# CSRF trusted origins for Railway
CSRF_TRUSTED_ORIGINS = [
    'https://*.railway.app',
    'https://railway.app',
] + [f'https://{host.strip()}' for host in ALLOWED_HOSTS if host.strip()]

# Security settings for Railway
SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
USE_X_FORWARDED_HOST = True
SECURE_SSL_REDIRECT = True

# Debug logging for Railway
import logging
logging.basicConfig(level=logging.INFO)
logger = logging.getLogger(__name__)

# Application definition

INSTALLED_APPS = [
    # 'admin_interface',  # временно отключено
    # 'colorfield',  # временно отключено
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # 'core',  # временно отключено
    # 'rangefilter',  # временно отключено
    # Новые приложения
    'authentication',
    'carwash',
    'carsharing',
    'warehouse',
    'accounting',
    'change_requests',
    'system_settings',
    'dashboard',
]

X_FRAME_OPTIONS = "SAMEORIGIN"

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Для статических файлов в продакшене
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# Создание суперпользователя при первом запуске
from django.contrib.auth import get_user_model

# Создаем суперпользователя если его нет
try:
    User = get_user_model()
    if not User.objects.filter(username='admin').exists():
        User.objects.create_superuser(
            username='admin',
            email='admin@carwash.local',
            password='admin123',
            first_name='Администратор',
            last_name='Системы'
        )
        print("✅ Суперпользователь создан: admin / admin123")
except Exception as e:
    print(f"⚠️  Не удалось создать суперпользователя: {e}")

# Debug logging для Railway
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
        },
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': 'INFO',
        },
        'django.request': {
            'handlers': ['console'],
            'level': 'DEBUG',
            'propagate': False,
        },
    },
}

ROOT_URLCONF = 'site1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'site1.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

# Настройки базы данных из переменной окружения
DATABASE_URL = os.getenv('DATABASE_URL', 'postgresql://postgres:MmuRktkaoQChhBECucfAhpIXqUaYFMxL@crossover.proxy.rlwy.net:42771/railway')

# Конфигурация базы данных
if DATABASE_URL:
    # Если DATABASE_URL установлена (Railway предоставляет PostgreSQL)
    import dj_database_url
    try:
        DATABASES = {
            'default': dj_database_url.config(default=DATABASE_URL)
        }
        logger.info("Using PostgreSQL database from Railway")
    except Exception as e:
        logger.error(f"Error configuring PostgreSQL: {e}")
        # Fallback to SQLite
        DATABASES = {
            'default': {
                'ENGINE': 'django.db.backends.sqlite3',
                'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
            }
        }
        logger.info("Fallback to SQLite database")
else:
    # Для локальной разработки или если DATABASE_URL не установлена
    DATABASES = {
        'default': {
            'ENGINE': 'django.db.backends.sqlite3',
            'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
        }
    }
    logger.info("Using SQLite database for development")

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'ru'

TIME_ZONE = 'Europe/Moscow'

USE_I18N = True

USE_L10N = True

USE_TZ = True

ADMIN_MEDIA_PREFIX = '/static/admin/'
# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/
STATIC_URL = '/static/'

# Директории со статическими файлами
STATICFILES_DIRS = [
    BASE_DIR / 'static',
]

# Папка для собранных статических файлов (для продакшена)
STATIC_ROOT = BASE_DIR / 'staticfiles'

# Настройки WhiteNoise для продакшена
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Медиа файлы
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Railway specific settings
# Port for Railway deployment
PORT = int(os.getenv('PORT', 8000))

# Debug logging for Railway
logger.info(f"Starting Django application on port {PORT}")
logger.info(f"DEBUG: {DEBUG}")
logger.info(f"ALLOWED_HOSTS: {ALLOWED_HOSTS}")
logger.info(f"DATABASE_URL: {os.getenv('DATABASE_URL', 'Not set')}")

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
