# Generated by Django 5.1.3 on 2025-12-27 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='admin_part',
            field=models.IntegerField(default=0, help_text='Фиксированная ставка администратора в рублях до преодоления порога кассы.', verbose_name='Ставка администратора'),
        ),
    ]
