# Generated by Django 5.1.3 on 2025-12-26 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('carwash', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('money', models.FloatField(default=0, verbose_name='Выплата')),
                ('shift', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='carwash.shift', verbose_name='Смена')),
                ('washman', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.washman', verbose_name='Мойщик')),
            ],
            options={
                'verbose_name': '$Выплаты мойщикам',
                'verbose_name_plural': '$Выплаты мойщикам',
            },
        ),
        migrations.CreateModel(
            name='OtherConsumption',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default='', max_length=32, verbose_name='Описание')),
                ('money', models.IntegerField(default=0, verbose_name='Сумма')),
                ('shift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='carwash.shift', verbose_name='Смена')),
            ],
            options={
                'verbose_name': '$Отчёты бытовые',
                'verbose_name_plural': '$Отчёты бытовые',
            },
        ),
    ]
